fyers:
  client_id: "4FBLV9KAQN-100"
  access_token: "3ZFR7SA8XZ"
  redirect_uri: "http://127.0.0.1:5000/"

telegram:
  bot_token: "8299955382:AAEhg6HGmGq57fKS7PeYcj0KH1nATcdnJBM"
  chat_id: "23687351"

