capital: 8000

risk:
  risk_per_trade_pct: 2
  daily_loss_pct: 5
  max_intraday_trades: 1

symbols:
  - NSE:NIFTYBANK-INDEX
  - NSE:NIFTY50-INDEX

telegram:
  token: "YOUR_TOKEN"
  chat_id: "YOUR_CHAT_ID"
